name: "Release js package to aws codeartifact"
description: "release javascript package"

inputs:
  github-token:
    description: "GITHUB token"
    required: true
  npm-token:
    description: "NPM token"
    required: true
  aws-access-key-id:
    description: "AWS access key id"
    required: false
  Aws-secret-access-key:
    description: "AWS secret access key"
    required: false
  aws-region:
    description: "AWS region"
    required: false

  codeartifact-domain:
    description: Codeartifact domain
    required: false
  codeartifact-owner:
    description: Codeartifact owner
    required: false
  working-directory:
    description: ""
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: codeartifact semantic-release
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        Aws_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_REGION: ${{ inputs.aws-region }}
        NPM_TOKEN: ${{ inputs.npm-token }}
        run: semantic-release --debug
        working-directory: ${{inputs.working-directory}}
