name: "Release js package to aws codeartifact"
description: "release javascript package"

inputs:
  npm-token:
    description: "NPM token"
    required: true
  working-directory:
    description: ""
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Install semantic-release
      shell: bash
      run: npm install -g semantic-release  @semantic-release/exec
      working-directory: ${{inputs.working-directory}}

    - name: "codeartifact semantic-release"
      env:
        AWS-ACCESS-KEY-ID: ${{ inputs.aws-access-key-id }}
        AWS-SECRET-ACCESS-KEY: ${{ inputs.aws-secret-access-key }}
        AS-REGION: ${{ inputs.aws-region }}
        GITHUB_TOKEN: ${{ github.token }}
        NPM_TOKEN: ${{ inputs.npm-token }}
      shell: bash
      run: semantic-release --debug
      working-directory: ${{inputs.working-directory}}
