name: "Setup Node and Yarn registry"
description: "Setup node, prepare local yarn and install dependencies"
inputs:
  node-version:
    description: Node version
    required: false
    default: "lts/*"

  install:
    description: "Install node dependencies [no|dev|prod|custom] default: no"
    required: false
    default: "no"

  codeartifact-domain:
    description: Codeartifact domain
    required: false
  codeartifact-owner:
    description: Codeartifact owner
    required: false

  aws-access-key-id:
    description: "AWS access key id"
    required: false
  aws-secret-access-key:
    description: "AWS secret access key"
    required: false
  aws-region:
    description: "AWS region"
    required: false

  working_directory:
    description: ""
    required: false
    default: "."

outputs:
  npm-token:
    description: "Codeartifact token"
    value: ${{steps.setup-codeartifact.outputs.AUTH_TOKEN}}

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{inputs.node-version}}

    - uses: The-AI-Institute-Bob/actions/setup-codeartifact@main
      if: ${{inputs.codeartifact-domain != '' && inputs.codeartifact-owner != ''}}
      with:
        aws-access-key-id: ${{inputs.aws-access-key-id}}
        aws-secret-access-key: ${{inputs.aws-secret-access-key}}
        aws-region: ${{inputs.aws-region}}
        codeartifact-domain: ${{inputs.codeartifact-domain}}
        codeartifact-owner: ${{inputs.codeartifact-owner}}
        working-directory: ${{inputs.working_directory}}

    - name: Install dependencies
      if: ${{inputs.install != 'no'}}
      working-directory: ${{inputs.working_directory}}
      shell: bash
      run: |
        if [ ${{inputs.install}} == 'dev' ]; then 
          yarn install
        elif [ ${{inputs.install}} == 'prod' ]; then 
          workspaces focus --production
        else
          eval ${{inputs.intall}}
        fi
