name: "Build publish docker"
description: "Build and publish docker to aws ECR"

inputs:
  ecr-registry:
    description: "AWS ECR registry"
    required: true
  ecr-repository:
    description: "AWS Repository name"
    required: true
  npm-token:
    description: "NPM token"
    required: false
    default: ""
  slack-webhook-url:
    description: "Slack Web hook url"
    required: slack
    default: ""
runs:
  using: composite
  steps:
    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ inputs.ecr-registry }}
        ECR_REPOSITORY: ${{ inputs.ecr-repository }}
        NPM_TOKEN: ${{ inputs.npm-token }}
      shell: bash
      run: |
        export TAG=`git describe --tags --abbrev=0`
        export SEMVERSION=${TAG:-"0.0.0"}
        docker build --build-arg NPM_TOKEN=$NPM_TOKEN -t "$ECR_REGISTRY/${ECR_REPOSITORY}:${GITHUB_SHA}" -t "$ECR_REGISTRY/${ECR_REPOSITORY}:latest" -t "$ECR_REGISTRY/${ECR_REPOSITORY}:${SEMVERSION}" .
        echo "Pushing image to ECR..."
        docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY
      working-directory: ${{ inputs.working-directory }}
    - name: Slack
      if: ${{inputs.slack-webhook-url != ''}}
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
         {
           "text": "docker container ${{ inputs.ecr-repository }} has been built: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
               {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
               }
            ]
         }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook-url }}
